version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mbh_php_app
    env_file:
      - .env
    # In production, we build the image with the code, so no need for volume mounts
    # volumes:
    #   - ${PWD}:/var/www/html
    networks:
      - app-network

  nginx:
    image: nginx:1.21-alpine
    container_name: mbh_nginx_server
    ports:
      - "80:80" # Changed to standard HTTP port
    volumes:
      # Mount the application code as a volume for Nginx to serve static assets and proxy to PHP-FPM
      - ./public:/var/www/html/public:ro # Assuming 'public' is your web root for Nginx
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - app
    networks:
      - app-network

  db:
    image: mysql:8.0
    container_name: mbh_mysql_db
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - db-data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  db-data:
    driver: local