name: Cloud Run Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Install Podman
      run: sudo apt-get update && sudo apt-get install -y podman
    - name: Build the Cloud Run image
      run: podman build -f cloud-run.Containerfile -t my-image-name:$(date +%s) .
